<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'PayerBankAccount' => 'Payer IBAN',
  'Amount' => 'Sum',
  'CancelPayment' => 'Cancel payment',
  'Continue' => 'Continue',
  'CreateDate' => 'Create date',
  'CreateTransaction' => 'Create transaction',
  'Currency' => 'Currency',
  'EventDate' => 'Due date',
  'ExchangeRate' => 'Exchange rate',
  'GetPayments' => 'Get payments',
  'GetTransactions' => 'Get transactions',
  'InsufficientSaldo' => 'Insufficient saldo',
  'InvalidDueDate' => 'Invalid due date',
  'InvalidIBANAccount' => 'Invalid IBAN account',
  'InvalidReferenceNumber' => 'Invalid reference number',
  'Message' => 'Message',
  'ModifyDate' => 'Modify date',
  'NewTransaction' => 'New transaction',
  'NoPaymentsForDue' => 'No payments for due.',
  'Payer' => 'Payer',
  'PayerBic' => 'Payer BIC',
  'PayerIban' => 'Payer IBAN',
  'PayerInfo' => 'Payer info',
  'PayerName' => 'Payer name',
  'PaymentInfo' => 'Payment Info',
  'PaymentsForDue' => 'Payments for due',
  'Recipient' => 'Recipient',
  'RecipientBic' => 'Recipient BIC',
  'RecipientIban' => 'Recipient IBAN',
  'RecipientInfo' => 'Recipient info',
  'RecipientName' => 'Recipient name',
  'ReferenceNumber' => 'Reference number',
  'ReferenceNumberOrMessageIsRequired' => 'Reference number or message is required',
  'RepaymentTooLow' => 'Repayment amount is too low',
  'TransactionSuccessful' => 'Transaction successful',
  'Transactions' => 'Transactions',
);
