<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Back' => '',
  'LoanDetails' => 'Loan details',
  'LoanPaymentPlan' => 'Loan payment plan',
  'Accept' => 'Accept',
  'AcceptDate' => 'Accept date',
  'Account' => 'Account',
  'Amount' => 'Amount',
  'ApplicationReceived' => 'Loan application received',
  'BankTransactionsBetween' => 'Bank transactions between',
  'Cancel' => 'Cancel',
  'CreateLoanApplication' => 'Create a loan application',
  'Decline' => 'Decline',
  'Details' => 'Details',
  'EndSaldo' => 'End saldo',
  'LoanAccount' => 'Loan account',
  'LoanApplications' => 'View loan applications',
  'Loans' => 'Loans',
  'PaymentPlan' => 'Payment plan',
  'StartSaldo' => 'Start saldo',
  'Summary' => 'Summary',
  'ThankYouMessage' => 'Thank you for applying!',
  'View' => 'View',
  'WeWillContactYou' => 'We will contact you as soon as the application is processed',
);
