<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'active' => 'Active',
  'annuity' => 'Annuity',
  'day' => 'Day',
  'days' => 'days',
  'declined' => 'Declined',
  'denied' => 'Denied',
  'fixedInstalment' => 'Fixed instalment',
  'fixedRepayment' => 'Fixed repayment',
  'granted' => 'Granted',
  'month' => 'Month',
  'months' => 'months',
  'open' => 'Open',
  'paid' => 'Paid',
  'removed' => 'Removed',
  'week' => 'Week',
  'weeks' => 'weeks',
  'year' => 'Year',
  'years' => 'years',
  '#' => '#',
  'AcceptDate' => 'Accept date',
  'Amount' => 'Loan amount',
  'ApplicationCreated' => 'Application created',
  'BankAccount' => 'Bank account',
  'BankInterest' => 'Loan interest',
  'BankUser' => 'Bank user',
  'CreateDate' => 'Create date',
  'CreateLoanApplication' => 'Create a loan application',
  'Currency' => 'Currency',
  'EventDay' => 'Event day',
  'GrantDate' => 'Grant date',
  'ID' => 'ID',
  'IncludesMargin' => 'Includes margin',
  'IndexLoanApplications' => 'Loan applications',
  'Instalment' => 'Instalment',
  'Interest' => 'Interest',
  'InterestUpdated' => 'Interest updated',
  'Interval' => 'Interval',
  'ModifyDate' => 'Modify date',
  'Principal' => 'Loan principal',
  'RealAmount' => 'Real amount',
  'Repayment' => 'Repayment',
  'Status' => 'Status',
  'Term' => 'Term',
  'TermInterval' => 'Term interval',
  'TotalInterest' => 'Total interest',
  'Type' => 'Loan type',
);
