<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'PayerBankAccount' => 'Maksajan IBAN',
  'Amount' => 'Summa',
  'CancelPayment' => 'Peru maksu',
  'Continue' => 'Jatka',
  'CreateDate' => 'Luontipäivä',
  'CreateTransaction' => 'Tee maksu',
  'Currency' => 'Valuutta',
  'EventDate' => 'Eräpäivä',
  'ExchangeRate' => 'Viitenumero',
  'GetPayments' => 'Hae maksut',
  'GetTransactions' => 'Hae tapahtumat',
  'InsufficientSaldo' => 'Tilin saldo ei riitä',
  'InvalidDueDate' => 'Virheellinen eräpäivä',
  'InvalidIBANAccount' => 'Virheellinen IBAN-tili',
  'InvalidReferenceNumber' => 'Virheellinen viitenumero',
  'Message' => 'Viesti',
  'ModifyDate' => 'Muokkausäivä',
  'NewTransaction' => 'Uusi maksu',
  'NoPaymentsForDue' => 'Ei erääntyviä maksuja.',
  'Payer' => 'Maksaja',
  'PayerBic' => 'Maksajan BIC',
  'PayerIban' => 'Maksajan IBAN',
  'PayerInfo' => 'Maksajan tiedot',
  'PayerName' => 'Maksajan nimi',
  'PaymentInfo' => 'Maksun tiedot',
  'PaymentsForDue' => 'Erääntyvät maksut',
  'Recipient' => 'Saaja',
  'RecipientBic' => 'Saajan BIC',
  'RecipientIban' => 'Saajan IBAN',
  'RecipientInfo' => 'Saajan tiedot',
  'RecipientName' => 'Saajan nimi',
  'ReferenceNumber' => 'Viitenumero',
  'ReferenceNumberOrMessageIsRequired' => 'Anna viitenumero tai viesti',
  'RepaymentTooLow' => 'Maksuerän suuruus ei riitä',
  'TransactionSuccessful' => 'Maksu suoritettu',
  'Transactions' => 'Tapahtumat',
);
