<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Back' => 'Takaisin',
  'LoanDetails' => 'Lainan tiedot',
  'LoanPaymentPlan' => 'Lainan takaisinmaksusuunnitelma',
  'Accept' => 'Hyväksy',
  'AcceptDate' => 'Myöntämispäivä',
  'Account' => 'Tili',
  'Amount' => 'Määrä',
  'ApplicationReceived' => 'Lainahakemus vastaanotettu',
  'BankTransactionsBetween' => 'Tilitapahtumat aikaväliltä',
  'Cancel' => 'Peruuta',
  'CreateLoanApplication' => 'Tee lainahakemus',
  'Decline' => 'Hylkää',
  'Details' => 'Tiedot',
  'EndSaldo' => 'Loppusaldo',
  'LoanAccount' => 'Lainatili',
  'LoanApplications' => 'Tarkastele lainahakemuksia',
  'Loans' => 'Lainat',
  'PaymentPlan' => 'Maksusuunnitelma',
  'StartSaldo' => 'Alkusaldo',
  'Summary' => 'Yhteenveto',
  'ThankYouMessage' => 'Kiitos hakemuksestasi!',
  'View' => 'Tarkastele',
  'WeWillContactYou' => 'Olemme sinuun yhteydessä heti kun hakemuksesi on käsitelty',
);
