<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '#' => '',
  'BankUser' => '',
  'Currency' => '',
  'ID' => '',
  'InterestUpdated' => '',
  'TermInterval' => '',
  'active' => 'Aktiivinen',
  'annuity' => 'Annuiteetti',
  'day' => 'Päivä',
  'days' => 'päivää',
  'declined' => 'Hylätty',
  'denied' => 'Hylätty',
  'fixedInstalment' => 'Tasalyhennys ',
  'fixedRepayment' => 'Kiinteä tasaerä',
  'granted' => 'Myönnetty',
  'month' => 'Kuukausi',
  'months' => 'kuukautta',
  'open' => 'Avoin',
  'paid' => 'Maksettu',
  'removed' => 'Poistettu',
  'week' => 'Viikko',
  'weeks' => 'viikkoa',
  'year' => 'Vuosi',
  'years' => 'vuotta',
  'AcceptDate' => 'Hyväksymispäivä',
  'Amount' => 'Lainan määrä',
  'ApplicationCreated' => 'Hakemus tehty',
  'BankAccount' => 'Pankkitili',
  'BankInterest' => 'Lainan korko',
  'CreateDate' => 'Luontipäivä',
  'CreateLoanApplication' => 'Tee lainahakemus',
  'EventDay' => 'Maksupäivä',
  'GrantDate' => 'Myöntämispäivä',
  'IndexLoanApplications' => 'Lainahakemukset',
  'Instalment' => 'Lyhennys',
  'Interest' => 'Korko',
  'Interval' => 'Maksuväli',
  'ModifyDate' => 'Muokkauspäivä',
  'Principal' => 'Lainapääoma',
  'RealAmount' => 'Todellinen määrä',
  'Repayment' => 'Maksuerä',
  'Status' => 'Tila',
  'Term' => 'Laina-aika',
  'TotalInterest' => 'Korko-osuus',
  'Type' => 'Lainatyyppi',
);
